---
# tasks file for wordpress
- name: install wordpress
  unarchive:
     src: https://wordpress.org/latest.tar.gz
     dest: /var/www/html
     remote_src: yes
  become: yes

- name: update Apache site
  lineinfile:
     dest: /etc/apache2/sites-enabled/000-default.conf
     regexp: "(.)+DocumentRoot /var/www/html"
     line: "DocumentRoot /var/www/html/wordpress"
  notify: Restart Apache
  become: yes
